import 'package:flutter/material.dart';
import '../repositories/car_repository.dart';
import 'car_detail_screen.dart';

class HomeScreen extends StatefulWidget{const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState();}
class _HomeScreenState extends State<HomeScreen>{final repo=CarRepository(); final search=TextEditingController(); List cars=[]; Map<String,double> dash={}; bool loading=true;
Future<void> load()async{setState(()=>loading=true); cars=await repo.cars(query:search.text); dash=await repo.dashboard(); setState(()=>loading=false);}
@override void initState(){super.initState();load();}
String money(double v)=>'${v.toStringAsFixed(0)} ₽';
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Auto Profit'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:()async{await Navigator.push(c,MaterialPageRoute(builder:(_)=>const CarDetailScreen()));load();},icon:const Icon(Icons.add),label:const Text('Автомобиль')),body:loading?const Center(child:CircularProgressIndicator()):Column(children:[Padding(padding:const EdgeInsets.all(12),child:TextField(controller:search,onChanged:(_)=>load(),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'VIN, госномер, марка или модель',border:OutlineInputBorder()))),Padding(padding:const EdgeInsets.symmetric(horizontal:12),child:Row(children:[_stat('Авто', '${dash['cars']?.toInt()??0}'),_stat('Вложено',money(dash['invested']??0)),_stat('Продажи',money(dash['revenue']??0)),_stat('Прибыль',money(dash['profit']??0))])),Expanded(child:cars.isEmpty?const Center(child:Text('Автомобилей пока нет')):ListView.builder(itemCount:cars.length,itemBuilder:(_,i){final car=cars[i]; return Card(margin:const EdgeInsets.symmetric(horizontal:12,vertical:5),child:ListTile(title:Text('${car.make} ${car.model}'),subtitle:Text('${car.status} • ${car.plate.isEmpty?'без номера':car.plate}'),trailing:const Icon(Icons.chevron_right),onTap:()async{await Navigator.push(c,MaterialPageRoute(builder:(_)=>CarDetailScreen(car:car)));load();},onLongPress:()async{await repo.deleteCar(car.id);load();}));})])]);
Widget _stat(String a,String b)=>Expanded(child:Padding(padding:const EdgeInsets.only(right:6),child:Card(child:Padding(padding:const EdgeInsets.all(9),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:11)),FittedBox(child:Text(b,style:const TextStyle(fontWeight:FontWeight.bold))) ])))));}
